### ISSUE TITLE
Support for Enterprise export of the audit log

### ISSUE THREAD

**Issue by droidpl** [github/ghec-audit-log-cli#18]
### Is your feature request related to a problem? Please describe
We currently only support the audit log in organizations. There is a [new API](https://docs.github.com/en/rest/reference/enterprise-admin#get-the-audit-log-for-an-enterprise) that would allow us to export the audit log from the enterprise itself.

### Describe the solution you'd like
Add a new parameter for enterprises, and make it an exclusive operation and only available for v3. That requires some extra validations that we can perform in the utils.

Docs need to be edited so the token has enterprise scope, otherwise it wouldn't work.

**Comment by froi** [comment]
@droidpl I'd like to take a look at this. Is there any status on it?

**Comment by droidpl** [comment]
I haven't made any progress yet so feel free to tackle it 😸

**Comment by nicklegan** [comment]
xref: https://github.com/githubcustomers/WPP/issues/18

**Comment by droidpl** [comment]
Fixed in #20
